Add {{range .Add}} {{.}}{{end}}

Cmd {{range .Cmd}} {{.}}{{end}}

Copy {{range .Copy}} {{.}}{{end}}

Entrypoint {{.Entrypoint}}
{{ range $key, $value := .Env }}
Env {{ $key }} {{ $value }}{{ end }}

Expose {{range .Expose}} {{.}}{{end}}

From {{.From}}
{{ range $key, $value := .Label }}
Label {{ $key }} {{ $value }}{{ end }}

Maintainer {{.Maintainer}}

Run {{range .Run}} {{.}}{{end}}

User {{.User}}

Volume {{range .Volume}} {{.}}{{end}}

Workdir {{.Workdir}}

